---
http_interactions:
- request:
    method: post
    uri: http://unix/v1.4/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["true"],"Image":"base"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MTM1
      !binary "RGF0ZQ==":
      - !binary |-
        VHVlLCAyOSBPY3QgMjAxMyAyMjowMDozMyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"290845cce7ec","Warnings":["Docker detected local DNS server
        on resolv.conf. Using default external servers: [8.8.8.8 8.8.4.4]"]}'
    http_version:
  recorded_at: Tue, 29 Oct 2013 22:00:33 GMT
- request:
    method: post
    uri: http://unix/v1.4/commit?container=290845cc
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        VHVlLCAyOSBPY3QgMjAxMyAyMjowMDozMyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"3d74951a6e7d"}'
    http_version:
  recorded_at: Tue, 29 Oct 2013 22:00:33 GMT
- request:
    method: post
    uri: http://unix/v1.4/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Image":"3d74951a6e7d"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MTM1
      !binary "RGF0ZQ==":
      - !binary |-
        VHVlLCAyOSBPY3QgMjAxMyAyMjowMDozMyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"7a362a381f09","Warnings":["Docker detected local DNS server
        on resolv.conf. Using default external servers: [8.8.8.8 8.8.4.4]"]}'
    http_version:
  recorded_at: Tue, 29 Oct 2013 22:00:33 GMT
- request:
    method: post
    uri: http://unix/v1.4/containers/7a362a381f09/start
    body:
      encoding: UTF-8
      string: ! '{}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOA==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MA==
      !binary "RGF0ZQ==":
      - !binary |-
        VHVlLCAyOSBPY3QgMjAxMyAyMjowMDozMyBHTVQ=
    body:
      encoding: US-ASCII
      string: ''
    http_version:
  recorded_at: Tue, 29 Oct 2013 22:00:33 GMT
- request:
    method: post
    uri: http://unix/v1.4/containers/7a362a381f09/attach?stdout=true&stream=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vdm5kLmRvY2tlci5yYXctc3RyZWFt
    body:
      encoding: US-ASCII
      string: ! '/

'
    http_version:
  recorded_at: Tue, 29 Oct 2013 22:00:33 GMT
recorded_with: VCR 2.6.0
