---
http_interactions:
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.6/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["true"],"Image":"base"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        VGh1LCAzMSBPY3QgMjAxMyAxODoxNzo0NyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"dc9e3ac95fc5"}'
    http_version: 
  recorded_at: Thu, 31 Oct 2013 18:17:47 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.6/commit?container=dc9e3ac9
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        VGh1LCAzMSBPY3QgMjAxMyAxODoxNzo0NyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"3a83fe5e49bf"}'
    http_version: 
  recorded_at: Thu, 31 Oct 2013 18:17:47 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.6/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Image":"3a83fe5e49bf"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        VGh1LCAzMSBPY3QgMjAxMyAxODoxNzo0NyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"ac8e28bf5cb0"}'
    http_version: 
  recorded_at: Thu, 31 Oct 2013 18:17:47 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.6/containers/ac8e28bf5cb0/start
    body:
      encoding: UTF-8
      string: ! '{}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOA==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MA==
      !binary "RGF0ZQ==":
      - !binary |-
        VGh1LCAzMSBPY3QgMjAxMyAxODoxNzo0NyBHTVQ=
    body:
      encoding: US-ASCII
      string: ''
    http_version: 
  recorded_at: Thu, 31 Oct 2013 18:17:47 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.6/containers/ac8e28bf5cb0/attach?stderr=true&stdout=true&stream=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vdm5kLmRvY2tlci5yYXctc3RyZWFt
    body:
      encoding: US-ASCII
      string: !binary |-
        AQAAAAAAAAIvCg==
    http_version: 
  recorded_at: Thu, 31 Oct 2013 18:17:47 GMT
recorded_with: VCR 2.7.0
