---
http_interactions:
- request:
    method: get
    uri: unix:///var/run/docker.sock/v1.6/version
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        NjM=
      !binary "RGF0ZQ==":
      - !binary |-
        RnJpLCAyNSBPY3QgMjAxMyAxNTo1NTozNyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Version":"0.6.4","GitCommit":"2f74b1c","GoVersion":"go1.1.2"}'
    http_version: 
  recorded_at: Fri, 25 Oct 2013 15:55:37 GMT
recorded_with: VCR 2.6.0
