---
http_interactions:
- request:
    method: get
    uri: unix:///var/run/docker.sock/v1.6/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjM2
      !binary "RGF0ZQ==":
      - !binary |-
        RnJpLCAyNSBPY3QgMjAxMyAxNjoyNDo0NyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Debug":false,"Containers":8,"Images":9,"NFd":10,"NGoroutines":13,"MemoryLimit":true,"IPv4Forwarding":true,"LXCVersion":"0.9.0","NEventsListener":12,"KernelVersion":"3.8.0-27-generic","IndexServerAddress":"https://index.docker.io/v1/"}'
    http_version: 
  recorded_at: Fri, 25 Oct 2013 16:24:47 GMT
recorded_with: VCR 2.6.0
